stages:
  data_ingestion:
    cmd: python src/package/pipeline/stage_01_data_ingestion.py
    deps:
      - src/package/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/ingestion
  data_validation:
    cmd: python src/package/pipeline/stage_02_data_validation.py
    deps:
      - src/package/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema/schema.yaml
    outs:
      - artifacts/data/validation
