from package.utils import read_yaml
from dataclasses import dataclass


CONFIG = read_yaml("config/config.yaml")

@dataclass
class DataIngestionConstants:
    ARITFACTS_ROOT_DIR_NAME = CONFIG.ARITFACTS_ROOT_DIR
    DATA_ROOT_DIR_NAME = CONFIG.DATA.ROOT_DIR
    INGESTION_ROOT_DIR_NAME = CONFIG.DATA.INGESTION.ROOT_DIR

    FEATURE_STORE_ROOT_DIR_NAME = CONFIG.DATA.INGESTION.FEATURE_STORE.ROOT_DIR
    RAW_FILE_NAME = CONFIG.DATA.INGESTION.FEATURE_STORE.RAW_FILE_NAME

    INGESTED_ROOT_DIR_NAME = CONFIG.DATA.INGESTION.INGESTED.ROOT_DIR
    TRAIN_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TRAIN_FILE_NAME
    TEST_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TEST_FILE_NAME

    SPLIT_RATIO = 0.2
    DATABASE_NAME = "Network-Security"
    COLLECTION_NAME = "Data"

